# Generated by Django 4.1.7 on 2023-03-08 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'task', 'verbose_name_plural': 'tasks'},
        ),
    ]
